IMAGE_NAME = "bento/ubuntu-20.04"
BOT_NUM = 1
BOT_CPU = 2
BOT_MEM = 2048

IP_BASE = "192.168.50."

VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  (1..BOT_NUM).each do |j|
    config.vm.define "devops-chat-#{j}" do |node|
      node.vm.box = IMAGE_NAME
      node.vm.network "private_network", ip: "#{IP_BASE}#{j + 10 + BOT_NUM}"
      node.vm.hostname = "devops-chat-#{j}"
    config.vm.network "forwarded_port", guest: 5000, host: 5000
    config.vm.provision :shell, path: "bootstrap.sh"  
    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = BOT_MEM
      v.cpus = BOT_CPU
      end
    end
  end
end

